### ISSUE TITLE
SynopticGroupStation' object is not subscriptable; Cannot cast array from dtype('O') to dtype('float64') according to the rule 'safe'

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris-synoptic#51]
```
Task id: 5d478c07-bb21-4244-95ad-36544977ea28

Traceback (most recent call last):
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'SynopticGroupStation' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1173, in pandas._libs.parsers.TextReader._convert_tokens
TypeError: Cannot cast array from dtype('O') to dtype('float64') according to the rule 'safe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/enhydris-openhi/enhydris_synoptic/tasks.py", line 11, in create_static_files
    render_synoptic_group(sgroup)
  File "/opt/enhydris-openhi/enhydris_synoptic/views.py", line 91, in render_synoptic_group
    _render_only_group(synoptic_group)
  File "/opt/enhydris-openhi/enhydris_synoptic/views.py", line 97, in _render_only_group
    output = render_to_string("enhydris-synoptic/group.html", context=context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/defaulttags.py", line 161, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
  File "/opt/enhydris-openhi/enhydris_synoptic/models.py", line 104, in synoptic_timeseries_groups
    self._determine_timeseries_groups()
  File "/opt/enhydris-openhi/enhydris_synoptic/models.py", line 116, in _determine_timeseries_groups
    start_date=start_date, end_date=self.last_common_date
  File "/opt/enhydris-openhi/enhydris/models.py", line 573, in get_data
    data = cache.get_or_set(f"timeseries_data_{self.id}", self._get_all_data_as_pd)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/django/core/cache/backends/base.py", line 167, in get_or_set
    default = default()
  File "/opt/enhydris-openhi/enhydris/models.py", line 603, in _get_all_data_as_pd
    return HTimeseries(StringIO(cursor.fetchone()[0])).data
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/htimeseries/htimeseries.py", line 340, in __init__
    self._read_filelike(data, **kwargs)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/htimeseries/htimeseries.py", line 347, in _read_filelike
    self.data = reader.get_data()
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/htimeseries/htimeseries.py", line 381, in get_data
    return TimeseriesRecordsReader(self.f, self.start_date, self.end_date).read()
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/htimeseries/htimeseries.py", line 403, in read
    data = self._read_data_from_stream(f2)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/htimeseries/htimeseries.py", line 432, in _read_data_from_stream
    dtype={"value": np.float64},
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 463, in _read
    data = parser.read(nrows)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 1154, in read
    ret = self._engine.read(nrows)
  File "/opt/enhydris-openhi/venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 2059, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 881, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 896, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 973, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1105, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1181, in pandas._libs.parsers.TextReader._convert_tokens
ValueError: cannot safely convert passed user dtype of float64 for object dtyped data in column 1
```

**Comment by aptiko** [comment]
This was fixed by installing a more recent version of pandas. It fails with pandas 0.25. The unit tests all pass regardless. Go figure. I'm not looking more into this.
