### ISSUE TITLE
TypeError: 'SynopticGroupStation' object is not subscriptable

### ISSUE THREAD

**Issue by aptiko** [openmeteo/enhydris-synoptic#54]
```


Task id: e0f1d649-a6d2-4faa-b781-a4968b477105

Traceback (most recent call last):
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'SynopticGroupStation' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/enhydris-openmeteo/enhydris_synoptic/tasks.py", line 11, in create_static_files
    render_synoptic_group(sgroup)
  File "/opt/enhydris-openmeteo/enhydris_synoptic/views.py", line 91, in render_synoptic_group
    _render_only_group(synoptic_group)
  File "/opt/enhydris-openmeteo/enhydris_synoptic/views.py", line 97, in _render_only_group
    output = render_to_string("enhydris-synoptic/group.html", context=context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 987, in render
    output = self.filter_expression.resolve(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/opt/enhydris-openmeteo/venv/lib/python3.7/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
  File "/opt/enhydris-openmeteo/enhydris_synoptic/models.py", line 164, in last_common_date_pretty_without_timezone
    return self.last_common_date and self.last_common_date.astimezone(
  File "/opt/enhydris-openmeteo/enhydris_synoptic/models.py", line 142, in last_common_date
    self._determine_last_common_date()
  File "/opt/enhydris-openmeteo/enhydris_synoptic/models.py", line 151, in _determine_last_common_date
    end_date = asyntsg.timeseries_group.default_timeseries.end_date
AttributeError: 'NoneType' object has no attribute 'end_date'
```

**Comment by aptiko** [comment]
This was actually an enhydris bug; fixed in enhydris#363.
